// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHome.Infrastructure.Persistence;

#nullable disable

namespace SmartHome.Infrastructure.Migrations
{
    [DbContext(typeof(SmartHomeDbContext))]
    [Migration("20260109113739_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("SmartHome.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Devices");

                    b.HasDiscriminator().HasValue("Device");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SmartHome.Domain.Entities.LightBulb", b =>
                {
                    b.HasBaseType("SmartHome.Domain.Entities.Device");

                    b.Property<bool>("IsOn")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("LightBulb");
                });

            modelBuilder.Entity("SmartHome.Domain.Entities.TemperatureSensor", b =>
                {
                    b.HasBaseType("SmartHome.Domain.Entities.Device");

                    b.Property<double>("CurrentTemperature")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("TemperatureSensor");
                });
#pragma warning restore 612, 618
        }
    }
}
